### ISSUE TITLE
Can we have a demo for multiple element?

### ISSUE THREAD

**Issue by donPuerto** [kevinwarne/vue-balloon#1]
Mulitple element like gmail... nice projects...

**Comment by kevinwarne** [comment]
Hmm I'm trying to think of how this would look. So you would have multiple containers grouped in a corner and each one could be clicked to expand into more of a full-window state? Is that what you had in mind?

**Comment by donPuerto** [comment]
Yes., your project is similar to Gmail... Better than Gmail I guess. 
![image](https://user-images.githubusercontent.com/9329005/32224427-56ecfe1c-be7c-11e7-9878-240e6799c013.png)

**Comment by kevinwarne** [comment]
Ah, that photo makes it much clearer. This functionality is not currently supported but it shouldn't be too difficult to add an option for this. I'll work on implementing something in the next day or two and report back. Thanks!

**Comment by kevinwarne** [comment]
Added a new BalloonSet component to handle the creation of multiple balloon elements on a page. There are a couple minor caveats that come with it. I've updated the documentation and updated on npm to version 1.0.18.
